name: progress_bar
description: Progress bar for dart command-line apps. A port of node-progress to Dart.
version: 0.2.0
author: Jaron Tai <jaroncn@gmail.com>
homepage: https://github.com/jarontai/progress_bar

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: ^0.12.0
